services:
  pricer-cpp:
    build:
      context: ./pricer-cpp
      dockerfile: Dockerfile
    image: pricer-cpp:local
    container_name: pricer-cpp
    volumes:
      - ./pricer-cpp:/app
    ports:
      - "9000:9000"
    restart: unless-stopped

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: hft-proxy:local
    container_name: hft-proxy
    depends_on:
      - pricer-cpp
    environment:
      PRICER_HOST: pricer-cpp
      PRICER_PORT: "9000"
      WS_PORT: "8080"
    volumes:
      - ./proxy:/app
    ports:
      - "8080:8080"
    restart: unless-stopped
  ui-react:
    build:
      context: ./ui-react
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./ui-react:/app
      - /app/node_modules
    restart: unless-stopped